language: node_js

node_js:
  - node

git:
  depth: false

install:
  # Install hub
  - sudo snap install hub --classic
  - hub --version

before_script:
  - yarn format:check
  - yarn lint
  - yarn build

script:
  - yarn test:coverage
  - yarn codecov
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$TRAVIS_BRANCH"; else echo "$TRAVIS_PULL_REQUEST_BRANCH"; fi)
  - if [ "$BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./scripts/compare.sh; fi

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - if [ -n "$NEXT" ] && [ "$NEXT" != "false" ]; then ./scripts/release.sh bump; fi
