version: '3.3'
services:
  db:
    image: 'postgres:13-alpine'
    container_name: 'example-pg'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'secret'

  app:
    container_name: 'example-app'
    build: .
