version: "3.3"

services: 
  mssql:
    container_name: "example-mssql"
    image: "mcr.microsoft.com/mssql/server:2017-GA-ubuntu"
    ports: 
      - "1433:1433"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}

  app:
    container_name: "example-app"
    environment:
      DEBUG: 'sync-db*'
    build: .
